32 t18 create order page 2/2
irtassedat/ecommerce pull request #34
Opened 2024-04-05 02:55 UTC by irtassedat

tamm anlamıyla içime sinmedi biraz daha görsel iyileştirmesi yapmam gerekecek fakat önceki turuncul halinden çook daha iyi gözüktüğü kesin

2024-05-01 14:28 UTC, gokhanozdemir requested changes

2024-05-01 14:28 UTC, gokhanozdemir commented on src/components/LayoutComponents/Header.jsx
LocalStorage işlemleri her render'da çalışmak yerine, örneğin useEffect ile kontrol edilmeli veya custom bir hook içinde yönetilmelidir. Bu, performansı ve kodun yeniden kullanılabilirliğini artırır.

2024-05-01 14:28 UTC, gokhanozdemir commented on src/components/LayoutComponents/Header.jsx
isLoggedIn state'i ve handleLogout fonksiyonunda kullanıcı oturumunu kontrol etmek için doğrudan localStorage kullanılıyor. Bu işlemler, daha güvenli bir yöntem olan Redux store üzerinden yönetilmelidir.

2024-05-01 14:28 UTC, gokhanozdemir commented on src/store/actions/shoppingCartAction.jsx
> +import {
Bunlar actionsdan import edilmeli

2024-06-01 22:41 UTC, irtassedat commented
@gokhanozdemir 
vercel failleri gerçekten çok fazla can sıkıyor farkındayım düzelteceğim fakat iş başvuruları dolasıyıla şuanda mergeliyorum.

2024-06-01 22:42 UTC, merged